#!/usr/bin/env node

var fs = require('fs')
var Web3 = require('web3')
var web3 = new Web3()
var repoABI = require('./contracts/MangoRepoABI.json')
var repoCode = fs.readFileSync('./contracts/MangoRepo.bin').toString()

var yargs = require('yargs')

yargs.usage('Usage: $0 [command]')
  .demand(1, 'Must provide a command')
  .option('R', {
    alias: 'repo',
    describe: 'Repository address',
    type: 'string'
  })
  .option('admin', {
    describe: 'Treat as administrator',
    type: 'boolean'
  })
  .option('account', {
    describe: 'Sender account (a current administrator)',
    type: 'string'
  })
  .command('status', 'Check status of repository')
  .command('create', 'Create repository')
  .command('obsolete', 'Mark repository obsolete')
  .command('authorize <address>', 'Authorize account with write access')
  .command('deauthorize <address>', 'Deauthorize account')
  .strict()
  .version()
  .showHelpOnFail(false, 'Specify --help for available options')
  .help()

var argv = yargs.argv
var command = argv._[0]

function abort (msg) {
  console.log(msg || 'Error occured')
  process.exit(1)
}

function ensureRepo () {
  if (!argv.repo) {
    abort('A repository address is mandatory for this operation')
  }

  if (!web3.isAddress(argv.repo)) {
    abort('Invalid repository address')
  }
}

function ensureAccount (account) {
  if (!account) {
    abort('An account is mandatory for this operation')
  }

  if (!web3.isAddress(account)) {
    abort('Invalid account')
  }
}

console.log('Initialising...')

web3.setProvider(new web3.providers.HttpProvider(process.env['ETHEREUM_RPC_URL'] || 'http://localhost:8545'))
if (!web3.eth.defaultAccount) {
  web3.eth.defaultAccount = web3.eth.coinbase
}

var from
if (argv.account) {
  ensureAccount(argv.account)
  from = argv.account
} else {
  from = web3.eth.defaultAccount
}

switch (command) {
  case 'create':
    console.log('Creating new repository with administrator ' + from)

    web3.eth.contract(repoABI).new({ data: repoCode, from: from }, function (err, contract) {
      if (err) {
        console.log('Error: ' + err)
        return
      }

      // Second callback will have the address
      if (contract.address) {
        console.log('Repository created: ' + contract.address)
      } else if (contract.transactionHash) {
        console.log('Sent transaction: ' + contract.transactionHash)
      }
    })

    break

  case 'status':
    console.log('Checking status of repository ' + argv.repo)
    ensureRepo()

    var contract = web3.eth.contract(repoABI).at(argv.repo)

    var version = contract.repoInterfaceVersion().toNumber()
    if (version !== 1) {
      abort('Not a Mango repository?')
    }

    if (web3.eth.contract(repoABI).at(argv.repo).isObsolete()) {
      console.log('Repository is marked as OBSOLETE')
    }

    var i
    var name
    var ref
    var refCount = contract.refCount().toNumber()

    if (!refCount) {
      console.log('No references')
    }

    for (i = 0; i < refCount; i++) {
      name = contract.refName(i)
      ref = contract.getRef(name)
      console.log('Reference: ' + name + ' -> ' + ref)
    }

    var snapshotCount = contract.snapshotCount().toNumber()

    if (!snapshotCount) {
      console.log('No snapshosts')
    }

    for (i = 0; i < snapshotCount; i++) {
      console.log('Snaphost #' + i + ': ' + contract.getSnapshot(i))
    }

    break

  case 'obsolete':
    console.log('Marking ' + argv.repo + ' as obsolete')
    ensureRepo()

    web3.eth.contract(repoABI).at(argv.repo).setObsolete({ from: from }, function (err, contract) {
      if (err) {
        console.log('Error: ' + err)
        return
      }

      console.log('Sent transaction: ' + contract)
    })

    break

  case 'authorize':
    console.log('Authorizing ' + argv.address + ' for ' + argv.repo + ' as ' + (argv.admin ? 'admin' : 'committer'))
    ensureRepo()
    ensureAccount(argv.address)

    web3.eth.contract(repoABI).at(argv.repo).authorize(argv.address, argv.admin, { from: from }, function (err, contract) {
      if (err) {
        console.log('Error: ' + err)
        return
      }

      console.log('Sent transaction: ' + contract)
    })

    break

  case 'deauthorize':
    console.log('Deauthorizing ' + argv.address + ' for ' + argv.repo + ' as ' + (argv.admin ? 'admin' : 'committer'))
    ensureRepo()
    ensureAccount(argv.address)

    web3.eth.contract(repoABI).at(argv.repo).deauthorize(argv.address, argv.admin, { from: from }, function (err, contract) {
      if (err) {
        console.log('Error: ' + err)
        return
      }

      console.log('Sent transaction: ' + contract)
    })

    break
}
